### ISSUE TITLE
code updatrs since 6/4?

### ISSUE THREAD

**Issue by nsulikowski** [microsoft/Trill#102]
the last nuget package dates 2019.7.24
but the last commit in this repo is 6/4
is this repo stale?

**Comment by cybertyche** [comment]
Not stale - we updated the NuGet to update the security certificate. Development is ongoing in the Provider branch at the moment for a major feature.

Sent from my pocket device

________________________________

**Comment by nsulikowski** [comment]
thanks
btw,
release notes would be great!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cybertyche** [comment]
Agreed, will try to do better in future releases. Still building some release cadence habits.
