### ISSUE TITLE
Parsing query language to derive Trill operation

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/Trill#158]
To the best of my knowledge, Azure Stream Analytics (ASA) is built atop Trill. The jobs themselves are configured in ASA by providing a query in the Stream Analytics Query Language. The query itself is presumably parsed behind the scenes and a Trill operation derived from it and run against the specified input and output(s).

Because the query itself is just a string, it's trivially serialized and propagated out to services for processing in a way that a Trill statement cannot be. Given that such serialization could be a pretty important part of how the distributed version (Quill) would have worked, was this functionality open sourced along with Trill itself?

**Comment by peterfreiling** [comment]
No, there is no plan to open source ASA code including compilation/serialization of the query.
