### ISSUE TITLE
Nuspec definition / assembly conflicts

### ISSUE THREAD

**Issue by jmajoor** [Microsoft/Trill#28]
The nuspec definitions for the net46 assembly do not seem to be in line with the net standard version.
For example it declares the following dependency:
<dependency id="Microsoft.CodeAnalysis.CSharp.Scripting" version="1.3.2" />

The net standard has far fewer dependencies listed and refers to 2.9.0.
The result is that I get assembly conflicts and use of the 1.3.2 version instead of the 2.9.0 version.

Could you update the nuspec definition and publish to nuget?

**Comment by cybertyche** [comment]
Absolutely - will try to do by the end of the week.

**Comment by jmajoor** [comment]
Thanks for the update. With this latest update I no longer have the assembly conflicts and methods that depend on the proper CodeAnalysis assembly versions are now working fine (on .net 472).
