### ISSUE TITLE
[Question] Ingress data from real-time source

### ISSUE THREAD

**Issue by huanbd** [Microsoft/Trill#31]
I have a real-time source to tracking links in a website, I have to collect the links have requested, and aggregate data (group, count...) according to each time period before save info(url, request count, ...) into a database. 
How can I use Trill in the best way on this case? I have read the sample, but they are offline ingress data, It only have a sample **RealTimeExample** but I can't apply to my case.
In case use Trill, I don't need save data permanently, I only need use Trill as a data buffer to aggregate (query/group/count...) of period time, after that data can be deleted.
Can you guide me how to use Trill in this case? Thank you

**Comment by cybertyche** [comment]
Absolutely. May I ask what interface is used by your real-time source?

The key is just to get the data into an IObservable<T> - once you have that, the path forward is identical to the offline cases.

**Comment by huanbd** [comment]
Hi @cybertyche thank you for your response
Oh, Now I understand that is `IObservable ` I have to deep into that
https://docs.microsoft.com/en-us/dotnet/standard/events/observer-design-pattern
https://docs.microsoft.com/en-us/dotnet/api/system.iobservable-1?view=netcore-2.2

_I will close this issue, and create other when I have question with Trill in my this case. Thank you_
