### ISSUE TITLE
Multiple tests break when machine's CultureInfo.CurrentCulture is not 'en-US'

### ISSUE THREAD

**Issue by nonmanifold** [Microsoft/Trill#32]
The following statement breaks tests on non-US machines:
https://github.com/Microsoft/Trill/blob/3ca9a12ec8386c1d58e6bd32a665ba41a6909769/Sources/Core/Microsoft.StreamProcessing/StringHandling/MultiString.cs#L108
Maybe it would help to configure test runner to use hardcoded culture if its unavoidable, and mention it in documentation?

Thank you.

**Comment by cybertyche** [comment]
Hi @nonmanifold , the restriction has been lifted with the latest merge.

**Comment by cybertyche** [comment]
Closing this issue for now - please reopen or file a new issue if something else comes up. Thank you for your help!
