### ISSUE TITLE
Cannot run performance test

### ISSUE THREAD

**Issue by buybackoff** [Microsoft/Trill#33]
Cannot run perf test. The error is in a generated file so cannot set a breakpoint and debug it easily as well. The code in the PerformanceTesting project hasn't changed since the initial commit and there is TODO in the generated file, so the question is if the test is supposed to work at all at the moment?

![image](https://user-images.githubusercontent.com/489852/50708949-2508d800-1077-11e9-8ccf-8f6938ed9705.png)

![image](https://user-images.githubusercontent.com/489852/50708836-c04d7d80-1076-11e9-8a8e-ce91123d688e.png)

**Comment by peterfreiling** [comment]
PR #34

**Comment by buybackoff** [comment]
I have `outputCount=0` on [this line](https://github.com/Microsoft/Trill/blob/d810b6e18e6bd292ab050b6cd439f47578cd18e6/Sources/Test/TrillPerf/Streamables/EquiJoinStreamablePerfTest.cs#L39) and printed performance at 1.8 billion input rows per second, which is about 2 CPU cycles per row and faster than a method call and doesn't look realistic.

**Comment by peterfreiling** [comment]
Thanks. This will be addressed by PR #35. I've verified that the output is produced and a realistic performance number is logged.

**Comment by buybackoff** [comment]
Thanks @peterfreiling. Still only the first test run prints sensible numbers. As if running the test has some side effect on inputs such as System.IO.Stream.Position...

The first run is cold and the number is lower than it should be. E.g. increasing row count by 10x increases the perf to c.10 MOPS.

![image](https://user-images.githubusercontent.com/489852/50883558-7a3b4580-13f9-11e9-8a8b-dfc1e51a6eda.png)

**Comment by peterfreiling** [comment]
Thanks @buybackoff, looks like this test has many issues! See PR #39.

**Comment by peterfreiling** [comment]
PR completed
