### ISSUE TITLE
Difficulty writing to and restoring from binary stream

### ISSUE THREAD

**Issue by nick-waterhouse** [Microsoft/Trill#41]
Is there any sample code available that demonstrates how to write to and read from binary streams?

Currently I have the following adapted from one of the existing Trill samples:

    var data = CreateStream(false);
    string filePath = @"C:\temp\trill_stream.bin";

    using (var stream = new FileStream(filePath, FileMode.Open))
    {
        data.ToBinaryStream(stream, true);
    }

    var fromFile = filePath.ToStreamableFromFile<SensorReading>();

    fromFile.ToStreamEventObservable().ForEachAsync(e => Console.WriteLine(e)).Wait();

When I run this code I get a null reference exception on that last line with the following stack trace:

    at Microsoft.StreamProcessing.StreamEventEgressPipe`1.OnNext(StreamMessage`2 batch) in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing\Egress\Temporal\TemporalEgressPipe.cs:line 28    
    at Microsoft.StreamProcessing.BinaryIngressReader`2.Ingress(IStreamObserver`2 observer) in D:\a\1\s\Sources\Core\Microsoft.StreamProcessing\Ingress\Binary\BinaryIngressReader.cs:line 69

**Comment by peterfreiling** [comment]
Thanks @nick-waterhouse , please refer to PR #42. There were a few issues this uncovered within Trill, and I've added an AdHoc test very similar to your code snippet.

However, you also have a bug in your code. When you call ToBinaryStream, you pass true for the writePropertiesToStream parameter (which defaults to false). However, when you deserialize via ToStreamableFromFile, you are defaulting to false for the readPropertiesFromStream parameter. These need to either both be true or both be false, or else the serialization will be misaligned.
