### ISSUE TITLE
NullReferenceException upon dispose subscription

### ISSUE THREAD

**Issue by jmajoor** [Microsoft/Trill#45]
I run into an exception when trying to dispose a subscription.
For example:
subscription = observableInput.ToAtemporalStreamable(TimelinePolicy.Sequence(1)).Count().ToStreamEventObservable().Where(c => c.IsData).Subscribe

My input feed will continue to deliver input data, but if I dispose of the subscription then this will result in a null reference exception.

I did some analysis on the codebase and noticed the following:
DisposeState method in SubscriptionBase will call the disposer?.Dispose() method. However the "disposer" field is never set.
In addition it releases the "currentBatch" buffer before any dispose call as well.

The result is that the currentBatch is set to null before the dispose call. This means another OnNext could happen and this will then result in a null reference on the currentBatch.

A possible solution is to make sure the "disposer" field is set to the subscription and the diposer?.Dispose() should be called first in the DisposeState method in order to properly dispose of the observable chain.

There is a second problem with the MonotonicSubscriptionWallClock. This will override the DisposeState method and never calls the base implementation, which means it never disposes of the subscription and keeps on processing events after the subscription has been disposed of.

**Comment by jmajoor** [comment]
TestCase:

The test case has a thread as a data feed and waits until at least one invocation occurs in the subscription. After this it will dispose the subscription (the input thread will keep running until canceled).

Expected behavior: The test to run to completion.

Actual behavior: A null reference exception due to the disposed currentBatch state and the non disposed observable.

[TestMethod, TestCategory("Gated")]
 public async Task DisposeTest1()
 {
       var cancelTokenSource = new CancellationTokenSource();
       var inputSubject = new Subject<int>();
       var lastSeenSubscription = 0;
       var observableInput = inputSubject.AsObservable();
       var inputTask = new Task(() =>
       {
            var n = 0;
            while (!cancelTokenSource.Token.IsCancellationRequested)
            {
                inputSubject.OnNext(++n);
                Thread.Sleep(10);
            }
            inputSubject.OnCompleted();
       });

       var semaphore = new SemaphoreSlim(0, 1);
       var subscription = observableInput.ToAtemporalStreamable(TimelinePolicy.Sequence(1)).Count().ToStreamEventObservable().Where(c => c.IsData).Subscribe(c =>
       {
           Interlocked.Exchange(ref lastSeenSubscription, (int)c.Payload);
           if (semaphore.CurrentCount == 0) semaphore.Release();
       });
       // Start the input feed.
       inputTask.Start();
       // Wait until we have at least one output data event.
       await semaphore.WaitAsync();
       // Dispose the subscription.
       subscription.Dispose();
       // Keep the input feed going, before cancel. This should behave properly if the subscription is disposed of properly.
       await Task.Delay(200);
       cancelTokenSource.Cancel();
       await inputTask;
       // Make sure we really got an output data event.
       Assert.IsTrue(lastSeenSubscription > 0);
  }

**Comment by cybertyche** [comment]
Good call on all accounts, @jmajoor. Checking in a fix shortly.

**Comment by cybertyche** [comment]
Issue should be fixed now! Thank you for your help!
