### ISSUE TITLE
Help calculating duration of condition

### ISSUE THREAD

**Issue by lothar7** [microsoft/Trill#53]
Trying to write code for a stream containing temperature values and if they are above a specified threshold (i.e 70 degrees) for more than 20 minutes, then output a "TEMPERATURE LIMIT EXCEEDED" error value. Once the condition is no longer satisfied, output a "TEMPERATURE NORMAL" value. 

Its probably quite straight forward but I currently struggling to work out how to approach this since I need to calculate the passing of time between values if the condition is met.

**Comment by cybertyche** [comment]
How is your input data formatted? Is it point events, where each temperature value is at a single time, or are the values intervals where each value has a begin time and an end time?

**Comment by lothar7** [comment]
Yes they are point events. This temperature values are from sensor readings. Each typically consists of 3 attributes: SensorName, TimeStamp, Value

**Comment by cybertyche** [comment]
Apologies for the delay - after some thought, I think the simplest way to express this is using Trill's automata feature. Let me construct an example, and I'll get back to you soon.

**Comment by cybertyche** [comment]
OK, here's a start - let's see if this can be used as a building block:

`        private struct SensorReading
        {
            public string Name;
            public long Timestamp;
            public double Value;
        }

        [TestMethod, TestCategory("Gated")]
        public void Sandbox()
        {
            var subject = new Subject<SensorReading>();
            var stream = subject.ToTemporalStreamable(o => o.Timestamp);
            var final = new List<object>();

            var pattern = stream.GroupApply(str => str.Name, str => str.DefinePattern()
                .SetRegister(new { MinTime = 0L, MaxTime = 0L })
                .SingleElement(o => o.Value > 70, (time, element, register) => new { MinTime = time, MaxTime = time })
                .KleeneStar(o => o.SingleElement((t, s, r) => s.Value > 70 && t - r.MinTime < 20, (time, element, register) => register))
                .KleenePlus(o => o.SingleElement((t, s, r) => s.Value > 70 && t - r.MinTime >= 20, (time, element, register) => new { register.MinTime, MaxTime = time }))
                .Detect(allowOverlappingInstances: false), (g, b) => new { Name = g.Key, Value = b });
            var output = pattern.ToStreamEventObservable().Where(o => o.IsData).ForEachAsync(o => final.Add(o));

            subject.OnNext(new SensorReading { Name = "a", Timestamp = 0, Value = 55 });
            subject.OnNext(new SensorReading { Name = "a", Timestamp = 1, Value = 55 });
            subject.OnNext(new SensorReading { Name = "a", Timestamp = 2, Value = 72 });
            subject.OnNext(new SensorReading { Name = "a", Timestamp = 3, Value = 55 });
            subject.OnNext(new SensorReading { Name = "a", Timestamp = 4, Value = 75 });
            subject.OnNext(new SensorReading { Name = "a", Timestamp = 5, Value = 79 });
            subject.OnNext(new SensorReading { Name = "a", Timestamp = 24, Value = 80 });
            subject.OnNext(new SensorReading { Name = "a", Timestamp = 25, Value = 80 });
            subject.OnNext(new SensorReading { Name = "a", Timestamp = 27, Value = 55 });
            subject.OnNext(new SensorReading { Name = "a", Timestamp = 28, Value = 72 });
            subject.OnNext(new SensorReading { Name = "a", Timestamp = 29, Value = 55 });
            subject.OnCompleted();
        }
`
