### ISSUE TITLE
question

### ISSUE THREAD

**Issue by nsulikowski** [microsoft/Trill#55]
i have a stream of the following 6 events
  A1 , B1 ,         B2 ,     A2 , B3 ,        B4
and I want to produce another stream of the B's, together with the last A's
         (B1,A1) , (B2,A1) ,     (B3,A2) , (B4,A2)
how can I go about it?

**Comment by cybertyche** [comment]
Hello! Yes, this is possible - let me think about the best way to do it and I'll get back to you shortly.

**Comment by nsulikowski** [comment]
Can't wait!

**Comment by nsulikowski** [comment]
anything?

**Comment by cybertyche** [comment]
`        private struct EventStruct
        {
            public string name;
            public int count;
            public override string ToString() => $"({name},{count})";
        }

        [TestMethod, TestCategory("Gated")]
        public void Sandbox()
        {
            var subject = new Subject<StreamEvent<EventStruct>>();
            var stream = subject.ToStreamable();
            var final = new List<object>();

            var pattern = stream.DefinePattern()
                .SetRegister(new { A = default(EventStruct), B = default(EventStruct) })
                .SingleElement(o => o.name == "A", (element, register) => new { A = element, B = default(EventStruct) })
                .KleenePlus(o => o.SingleElement(s => s.name == "B", (element, register) => new { register.A, B = element }))
                .Detect(100);
            var output = pattern.ToStreamEventObservable().Where(o => o.IsData).ForEachAsync(o => final.Add(o));

            subject.OnNext(StreamEvent.CreateStart(1, new EventStruct { name = "A", count = 1 }));
            subject.OnNext(StreamEvent.CreateStart(10, new EventStruct { name = "B", count = 1 }));
            subject.OnNext(StreamEvent.CreateStart(20, new EventStruct { name = "B", count = 2 }));
            subject.OnNext(StreamEvent.CreateStart(25, new EventStruct { name = "A", count = 2 }));
            subject.OnNext(StreamEvent.CreateStart(30, new EventStruct { name = "B", count = 3 }));
            subject.OnNext(StreamEvent.CreateStart(32, new EventStruct { name = "B", count = 4 }));
            subject.OnCompleted();
        }
`

**Comment by nsulikowski** [comment]
Amazing... thanks!
