### ISSUE TITLE
XML documentation missing in netstandard2.0

### ISSUE THREAD

**Issue by sehra** [Microsoft/Trill#65]
For the netstandard2.0 build, the XML documentation is missing in the NuGet package.

**Comment by cybertyche** [comment]
.nuspec has been updated - waiting for an infrastructure issue to clear before uploading a new NuGet package

**Comment by cybertyche** [comment]
OK, a new NuGet has been pushed. Take a look when you get a chance!

**Comment by sehra** [comment]
Works fine now, thanks.
