### ISSUE TITLE
left outer join

### ISSUE THREAD

**Issue by nsulikowski** [Microsoft/Trill#67]
I'd like to do a LEFT OUTER JOIN between two streams
It looks like I could use DefinePattern. Is there any other better way?
Thanks,
Nestor

**Comment by peterfreiling** [comment]
Hi Nestor, have you tried the LeftOuterJoin macro? https://github.com/Microsoft/Trill/blob/master/Sources/Core/Microsoft.StreamProcessing/StreamableAPI/StreamableExtensions.cs#L984

**Comment by nsulikowski** [comment]
Great. Thanks!
