### ISSUE TITLE
Does not have a valid equality operator for columnar mode

### ISSUE THREAD

**Issue by nsulikowski** [microsoft/Trill#72]
I changed my payload from struct to class, and now after doing a join I get the error:
Type of left side of join, 'xxxxxxx', does not have a valid equality operator for columnar mode.
Can you help me fast? (usually it takes many days to get a reply here... it'd be great to either have better documentation, or more prompt responses … thanks much)

**Comment by cybertyche** [comment]
Trying to reply within a day, will try to go even faster.

I believe the solution is to make sure your class overrides Equals.

**Comment by cybertyche** [comment]
More details (wanted to get the previous answer quickly out there in case you're online and in a rush):

The Join operator in columnar execution needs to be able to reason about whether payloads are equal, and doing so by reference equality in columnar mode just doesn't work. There are a few ways that Trill recognizes if there is a valid equality "operator":

- If the type implements `IEquatable<T>` (simplest for the implementer)
- If the type implements `Microsoft.StreamProcessing.IEqualityComparerExpression<T>` (easiest for Trill to work with for code generation, but by far the hardest for the implementer)
- If the type has overridden Equals and GetHashCode methods (least preferable but we'll work with it)

An alternative solution is to turn off columnar execution. You can do that by setting Config.ForceRowBasedExecution to true.

**Comment by nsulikowski** [comment]
that’s what i thought
but i still get the exception after implementing IEquitable<T>  and even Equals/GetHashCode

(Im using the LeftOuterJoin)

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by cybertyche** [comment]
Ah! Looking at the code, it appears there may be a bug there. One moment, verifying. I think it's looking at and testing the wrong type.

**Comment by mike-barnett** [comment]
We (@cybertyche and I) just looked at the code together and we are very unclear on whether there is actually a bug in the code or not. Would it be possible for you to post an (extremely short) repro here so we can dig into it? Sorry for the problem!

**Comment by nsulikowski** [comment]
Try this:

````
        public class IONRecord_Class_WithEquality : IEquatable<IONRecord_Class_WithEquality>
        {
            public string Id;
            public string Data;
 
            public bool Equals(IONRecord_Class_WithEquality other)
            {
                if (other == null) return false;
                return Id == other.Id && Data == other.Data;
            }
            public override bool Equals(object obj)
            {
                return Equals(obj as IONRecord_Class_WithEquality);
            }
            public override int GetHashCode()
            {
                unchecked
                {
                    var hashcode = 83;
                    hashcode = (hashcode * 89) + (this.Id != null ? this.Id.GetHashCode() : 0);
                    hashcode = (hashcode * 89) + (this.Data != null ? this.Data.GetHashCode() : 0);
                    return hashcode;
                }
            }
            public static bool operator == (IONRecord_Class_WithEquality first, IONRecord_Class_WithEquality second) => first.Equals(second);
            public static bool operator != (IONRecord_Class_WithEquality first, IONRecord_Class_WithEquality second) => !first.Equals(second);
 
            public override string ToString() => $" {{{nameof(Id)}:{Id}, {nameof(Data)}:{Data}}}";
        }
 
        [Fact]
        public void LeftOuterJoin_WithEquality_Test()
        {
            var assets_subject = new Subject<StreamEvent<IONRecord_Class_WithEquality>>();
            var iconnect_subject = new Subject<StreamEvent<IONRecord_Class_WithEquality>>();
 
            var assets_stream = assets_subject.ToStreamable(disorderPolicy: DisorderPolicy.Throw(), flushPolicy: FlushPolicy.FlushOnPunctuation, periodicPunctuationPolicy: null);
            var iconnect_stream = iconnect_subject.ToStreamable(disorderPolicy: DisorderPolicy.Throw(), flushPolicy: FlushPolicy.FlushOnPunctuation, periodicPunctuationPolicy: null);
 
            //It shouldn't throw... but is still does
            //Type of left side of join, 'Release_Tests.Trill_Equality_Tests+IONRecord_NoEquality', does not have a valid equality operator for columnar mode
            Assert.Throws<InvalidOperationException>(() =>
            {
                var output_stream = assets_stream
                    .LeftOuterJoin(right: iconnect_stream,
                                   leftKeySelector: a => a.Id,
                                   rightKeySelector: i => i.Id,
                                   outerResultSelector: a => new
                                   {
                                       a_Id = a.Id,
                                       i_Id = (string)null
                                   },
                                   innerResultSelector: (a, i) => new
                                   {
                                       a_Id = a.Id,
                                       i_Id = i.Id
                                   });
            });
        }
````

**Comment by cybertyche** [comment]
After running the above code, what I surmise is that simply implementing `IEquatable<T>` is not sufficient for the check as I had surmised. We actually need the implementation of `IEqualityComparerExpression<T>`. Which is, of course, completely non-obvious from the error message or even a cursory look at the code.

The issue, unless @mike-barnett has more info than I, is that to do efficient code generation for columnar mode, we need to be able to inspect the expressions for equality and hash code to be able to manipulate them and inline them into the generated code. Without that ability, we would need to be re-packaging each payload one at a time to do the equality check, which is kind of pointless in columnar.

In debugging this issue, I did find two issues that @mike-barnett and I are going to work on, but I did get code running that works:

`
        public class IONRecord_Class_WithEquality : IEqualityComparerExpression<IONRecord_Class_WithEquality>
        {
            public string Id;
            public string Data;

            public bool Equals(IONRecord_Class_WithEquality other)
            {
                if (other == null) return false;
                return Id == other.Id && Data == other.Data;
            }
            public override bool Equals(object obj)
            {
                return Equals(obj as IONRecord_Class_WithEquality);
            }
            public override int GetHashCode()
            {
                unchecked
                {
                    var hashcode = 83;
                    hashcode = (hashcode * 89) + (this.Id != null ? this.Id.GetHashCode() : 0);
                    hashcode = (hashcode * 89) + (this.Data != null ? this.Data.GetHashCode() : 0);
                    return hashcode;
                }
            }
            public static bool operator ==(IONRecord_Class_WithEquality first, IONRecord_Class_WithEquality second) => first.Equals(second);
            public static bool operator !=(IONRecord_Class_WithEquality first, IONRecord_Class_WithEquality second) => !first.Equals(second);

            public override string ToString() => $" {{{nameof(Id)}:{Id}, {nameof(Data)}:{Data}}}";

            public Expression<Func<IONRecord_Class_WithEquality, IONRecord_Class_WithEquality, bool>> GetEqualsExpr()
                => (left, right) => left.Data == right.Data && left.Id == right.Id;

            public Expression<Func<IONRecord_Class_WithEquality, int>> GetGetHashCodeExpr()
                => (that) => ((83
                    * 89) + (that.Id != null ? that.Id.GetHashCode() : 0)
                    * 89) + (that.Data != null ? that.Data.GetHashCode() : 0);
        }

        [TestMethod, TestCategory("Gated")]
        public void LeftOuterJoin_WithEquality_Test()
        {
            var assets_subject = new Subject<StreamEvent<IONRecord_Class_WithEquality>>();
            var iconnect_subject = new Subject<StreamEvent<IONRecord_Class_WithEquality>>();

            var assets_stream = assets_subject.ToStreamable(disorderPolicy: DisorderPolicy.Throw(), flushPolicy: FlushPolicy.FlushOnPunctuation, periodicPunctuationPolicy: null);
            var iconnect_stream = iconnect_subject.ToStreamable(disorderPolicy: DisorderPolicy.Throw(), flushPolicy: FlushPolicy.FlushOnPunctuation, periodicPunctuationPolicy: null);

            // It shouldn't throw... but is still does
            // Type of left side of join, 'xxx', does not have a valid equality operator for columnar mode
                var output_stream = assets_stream
                    .LeftOuterJoin(
                                   right: iconnect_stream,
                                   leftKeySelector: a => a.Id,
                                   rightKeySelector: i => i.Id,
                                   outerResultSelector: a => new
                                   {
                                       a_Id = a.Id,
                                       i_Id = (string)null
                                   },
                                   innerResultSelector: (a, id) => new
                                   {
                                       a_Id = a.Id,
                                       i_Id = id.Id
                                   });
        }
`

**Comment by nsulikowski** [comment]
BTW, Your fix makes Trill thow a new exception

**Comment by cybertyche** [comment]
PR for fix incoming.

**Comment by cybertyche** [comment]
Fix pushed to NuGet.

**Comment by nsulikowski** [comment]
here is another unintended bug, it seems:

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by cybertyche** [comment]
I'm not seeing the cast exception when running your code locally. Instead, I'm seeing it throw due to the class implementing IEquatable instead of IEqualityComparerExpression. The invalid cast you're seeing is consistent with behavior before the NuGet published a few hours ago.

**Comment by cybertyche** [comment]
Never mind, I can repro - I had test settings set up differently than you. One moment.

**Comment by nsulikowski** [comment]
If i implement IEqualityComparerExpression the error goes away though...

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by cybertyche** [comment]
Well, the exception message has been fixed as has the issue you were seeing just above. New NuGet pushed.

**Comment by nsulikowski** [comment]
confirmed that it works!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
