### ISSUE TITLE
Global SyncTime

### ISSUE THREAD

**Issue by nsulikowski** [microsoft/Trill#74]
Does Trill have one notion of time across all streams or only per stream?
If it does, is there a way to access that long property?

**Comment by cybertyche** [comment]
The notion of sync time is per stream, right up until any binary operator in which case they must be considered the same. That notion is entirely data-driven - there is no notion of sync time that is somehow managed by the query or the engine itself.

You can absolutely access that long property - you can lift it into your payload using an overload of Select whose lambda takes two parameters. It looks like: `stream.Select((sync, payload) => ...)`

**Comment by nsulikowski** [comment]
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
