### ISSUE TITLE
SyncTime public?

### ISSUE THREAD

**Issue by nsulikowski** [Microsoft/Trill#82]
I’d submit that SyncTime and OtherTime should not be internal but public in the StreamEvent struct.
They are both integral concepts of the library.

**Comment by peterfreiling** [comment]
These concepts are readily available via StreamEvent.StartTime/EndTime or PartitionedStreamEvent.StartTime/EndTime properties, which abstract a potential confusion for end-edge events, where SyncTime is the end time and OtherTime is the original start time corresponding to the end-edge.
