### ISSUE TITLE
How do i do a full join?

### ISSUE THREAD

**Issue by nsulikowski** [microsoft/Trill#85]
There is Join(...) and LeftOuterJoin(...)
How about FullJoin ?

**Comment by cybertyche** [comment]
Within Trill, LeftOuterJoin is implemented as a helper method over three operations:

- EquiJoin
- LeftAntiSemiJoin (WhereNotExists)
- Union

It looks just like this:

`
        public static IStreamable<TKey, TResult> LeftOuterJoin<TKey, TLeft, TRight, TJoinKey, TResult>(
            this IStreamable<TKey, TLeft> left,
            IStreamable<TKey, TRight> right,
            Expression<Func<TLeft, TJoinKey>> leftKeySelector,
            Expression<Func<TRight, TJoinKey>> rightKeySelector,
            Expression<Func<TLeft, TResult>> outerResultSelector,
            Expression<Func<TLeft, TRight, TResult>> innerResultSelector)
        {
            Invariant.IsNotNull(left, nameof(left));
            Invariant.IsNotNull(right, nameof(right));

            return left.Multicast(right, (l_mc, r_mc) =>
            {
                var lasj = l_mc.WhereNotExists(r_mc, leftKeySelector, rightKeySelector).Select(outerResultSelector);
                var innerJoin = l_mc.Join(r_mc, leftKeySelector, rightKeySelector, innerResultSelector);
                return lasj.Union(innerJoin);
            });
        }
`

So adding a FullOuterJoin method can be done from extending the code above with a second WhereNotExists and a second Union operation, plus another selector expression in the method signature.

Any interest in writing a PR to contribute this to the public API? :-) We'd help you through it if you are so inclined.

**Comment by nsulikowski** [comment]
There is nothing i d love more
but im at work all day, and i wouldn’t be able to do it from here :-(

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by cybertyche** [comment]
Eep, sorry, for some reason I didn't get your edited comment, only the original one.

I'm relatively new to GitHub myself, but I think the way to do it is to create your own branch (in this repo if you can) and create a pull request from the web interface. I've not created a PR from visual studio directly.

**Comment by NickDarvey** [comment]
@nsulikowski, @cybertyche for external contributors the pattern is usually to fork the repo [then submit a pull request from the fork](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork).

If you've made the change already to an (unforked) clone of the repo locally, you can fork the repo from GitHub then update your local clone's origin to point at your fork ([same as shown here, though it's for Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/repos/git/repo-rename?view=azure-devops#update-the-git-remotes-on-your-dev-machines)]. You should then be able to push your changes (to your fork) and open a pull request (from your fork to the original).

**Comment by cybertyche** [comment]
Nicely done, @nsulikowski ! And thank you for the assist, @NickDarvey .
